sudo: false
language: php
php:
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6" # Toolforge k8s webservice
install:
  - composer install
  - npm install
script:
  - composer test
  - npm test
notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-labs"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit}: %{author}) %{message} - %{build_url}"
