sudo: false
language: php
php:
  - "5.6"
  - "5.5"
  - "hhvm"
install:
  - composer install
  - npm install
script:
  - composer test
  - npm test
notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-labs"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit}: %{author}) %{message} - %{build_url}"
